import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;

public class firstInclude extends HttpServlet{

 public void doGet(HttpServletRequest req,HttpServletResponse res)
            throws ServletException,IOException
 {
	   res.setContentType("text/html");
	   PrintWriter out = res.getWriter();

	   out.println("<html><head><title>SSI </title></head>");



	   out.println("<body><h1>This line is generated by FirstInc page.</h1><br><br><br>");





	   String name = "From FirstInc Servlet";
	   req.setAttribute("source", name);
	     
	   RequestDispatcher rd = req.getRequestDispatcher("/secondInclude");
	   rd.include(req,res);





	   out.println("<br><br><br><h1>Again This line is generated by FirstInc page.</h1></body></html>");

 }
}
